function [calibrated_image_array_downsampled,...
                calibrated_frame_array_downsampled] =...
                        generate_downsampled_arrays(file_identifiers,...
                        calibrated_image_array, calibrated_frame_array,...
                        downsample_factor)
    calibrated_image_array_downsampled = containers.Map;
    calibrated_frame_array_downsampled = containers.Map;
    for i = 1:length(file_identifiers)
        file_identifier = file_identifiers{i};
        calibrated_image_array_downsampled(file_identifier) =...
                downsample_array(calibrated_image_array(file_identifier),...
                                                        downsample_factor);
        calibrated_frame_array_downsampled(file_identifier) =...
                downsample_array(calibrated_frame_array(file_identifier),...
                                                        downsample_factor);
    end
end