function keep_power_array = generate_keep_power_array(measured_power_array,...
                                            reference_power_array,...
                                            keep_power, num_dims)
    avg_power_per_percent = measured_power_array/reference_power_array;
    keep_percent_power_array = linspace(keep_power(1), keep_power(end),...
                                                                num_dims);
    keep_power_array = keep_percent_power_array .* avg_power_per_percent;
end